#!/bin/bash
###############################################################################
# MONIO - Met Office NetCDF Input Output                                      #
#                                                                             #
# (C) Crown Copyright 2023, Met Office. All rights reserved.                  #
#                                                                             #
# This software is licensed under the terms of the 3-Clause BSD License       #
# which can be obtained from https://opensource.org/license/bsd-3-clause/.    #
###############################################################################
set -euxo pipefail

finally() {
    trap '' ERR
    trap '' EXIT
    if [[ -d "${WORKD:-}" ]]; then
        cd /
        rm -fr "${WORKD}"
    fi
}

# HERE is /usr/local/src/<REPONAME>/pr-<#> (cf ../.github/workflow/ci.yml)
HERE="$(cd "$(dirname "$0")" && pwd)"
THIS="$(basename "$0")"
NPROC=${NPROC:-$(nproc)}
WORKD="$(mktemp -d "${THIS}-XXXXXX" -t)"
GENERATOR=Unix\ Makefiles
if command -v ninja &>/dev/null; then GENERATOR=Ninja; fi
BASE="${HERE%/*}"
TESTDIR="${BASE##*/}"
export OMPI_MCA_rmaps_base_oversubscribe=true
export MONIO_TESTFILES_DIR="/var/tmp/MOBB_DATA/lfric-lite/Data"
ls -l "${MONIO_TESTFILES_DIR}"

trap finally ERR EXIT
cd "${WORKD}"

# -- Activate spack env if using JCSDA Docker container 
if [[ -f /opt/spack-environment/activate.sh ]]; then
    source /opt/spack-environment/activate.sh
fi

# -- Configure
cmake -B . -S "${HERE}" -G "${GENERATOR}" -DCMAKE_BUILD_TYPE=Debug 

# -- Build
cmake --build . -j "${NPROC}"

# -- Test
env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
ctest -j"${NPROC}" --test-dir "${TESTDIR}" || \
env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
ctest --test-dir "${TESTDIR}" --rerun-failed -V

exit
