#!/bin/bash
#
# (C) Crown Copyright 2023, the Met Office. All rights reserved.
#
set -euxo pipefail

finally() {
    trap '' ERR
    trap '' EXIT
    if [[ -d "${WORKD:-}" ]]; then
        cd /
        rm -fr "${WORKD}"
    fi
}

HERE="$(cd "$(dirname "$0")" && pwd)"
THIS="$(basename "$0")"
NPROC=${NPROC:-$(nproc)}
WORKD="$(mktemp -d "${THIS}-XXXXXX" -t)"
GENERATOR=Unix\ Makefiles
if command -v ninja &>/dev/null; then GENERATOR=Ninja; fi

trap finally ERR EXIT

cd "${WORKD}"

# -- Activate spack env if using JCSDA Docker container 
if [[ -f /opt/spack-environment/activate.sh ]]; then
    source /opt/spack-environment/activate.sh
fi

ls -l /var/tmp
du -hd 2 /var/tmp
ls -l /var/tmp/model-interface-data

export LFRICLITE_DATA_REP_DIR=/var/tmp/model-interface-data/lfric-lite/Data

# -- Configure
cmake -B . -S "${HERE}" -G "${GENERATOR}" \
    -DCMAKE_BUILD_TYPE=Debug \
    -DMPI_ARGS="--oversubscribe"

# -- Build
cmake --build . -j "${NPROC}"

# -- Test
env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
ctest -j"${NPROC}" --test-dir './monio' -V

# env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
# ctest -j"${NPROC}" --test-dir './monio' || \
# env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
# ctest --test-dir './monio' --rerun-failed -V

exit
