---
name: UKMO_CI_Azure

on:
  push:
    branches: [master]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: jedi-self-hosted-rg
    steps:
      - name: checkout current
        uses: actions/checkout@v4
        with:
          path: bundle/monio

      - name: checkout jedicmake
        uses: actions/checkout@v4
        with:
          path: bundle/jedicmake
          repository: JCSDA-internal/jedi-cmake
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: checkout oops
        uses: actions/checkout@v4
        with:
          path: bundle/oops
          repository: JCSDA-internal/oops
          token: ${{ secrets.GH_PAT }}
      - name: matching branch checkout attempt oops ${{ github.head_ref }}
        if: github.event_name == 'pull_request'
        run: ./ci/get-ref-branch ./bundle/oops

      # - name: checkout monio
      #   uses: actions/checkout@v4
      #   with:
      #     path: ci/monio
      #     repository: MetOffice/monio
      #     token: ${{ secrets.GH_PAT }}
      # - name: matching branch checkout attempt monio ${{ github.head_ref }}
      #   if: github.event_name == 'pull_request'
      #   run: ./ci/get-ref-branch ./ci/monio

      - name: build and lint
        run: |
          az acr login --name ngmssboxjediacr
          docker run --rm \
            --entrypoint=/usr/local/src/monio-ci/ci/build-and-test \
            --workdir=/usr/local/src/monio-ci/ci \
            --volume $PWD:/usr/local/src/monio-ci \
            'ngmssboxjediacr.azurecr.io/jedibase:alma9'
