# ci.yml
---
name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

env:
  REPO: ${{ github.event.repository.name }}
  BUNDLE: pr-${{ github.event.number }}  

jobs:
  build1:
    if: github.repository_owner == 'MetOffice'
    name: gnu-openmpi (JCSDA)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current
        uses: actions/checkout@v4
        with:
          path: ./${{ env.BUNDLE }}/${{ env.REPO }}
      - name: initiate bundle
        run: cp ./${{ env.BUNDLE }}/${{ env.REPO }}/ci/* ./${{ env.BUNDLE }}/

      - name: Checkout jedicmake
        uses: actions/checkout@v4
        with:
          path: ./${{ env.BUNDLE }}/jedicmake
          repository: JCSDA-internal/jedi-cmake
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Checkout oops
        uses: actions/checkout@v4
        with:
          path: ./${{ env.BUNDLE }}/oops
          repository: JCSDA-internal/oops
          token: ${{ secrets.GH_PAT }}
      - name: Checkout attempt for oops@${{ github.head_ref }}
        if: github.event_name == 'pull_request'
        run: ./${{ env.BUNDLE }}/get-ref-branch ./${{ env.BUNDLE }}/oops

      - name: Build and Lint
        run: |
          docker run --rm \
            --entrypoint=/usr/local/src/${REPO}/${BUNDLE}/build-and-lint \
            --workdir=/usr/local/src/${REPO}/${BUNDLE} \
            --volume ${PWD}/${BUNDLE}:/usr/local/src/${REPO}/${BUNDLE} \
            'jcsda/docker-gnu-openmpi-dev:latest'

  build2:
    if: github.repository_owner == 'MetOffice'
    name: clang-mpich (JCSDA)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current
        uses: actions/checkout@v4
        with:
          path: ./${{ env.BUNDLE }}/${{ env.REPO }}
      - name: initiate bundle
        run: cp ./${{ env.BUNDLE }}/${{ env.REPO }}/ci/* ./${{ env.BUNDLE }}/

      - name: Checkout jedicmake
        uses: actions/checkout@v4
        with:
          path: ./${{ env.BUNDLE }}/jedicmake
          repository: JCSDA-internal/jedi-cmake
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Checkout oops
        uses: actions/checkout@v4
        with:
          path: ./${{ env.BUNDLE }}/oops
          repository: JCSDA-internal/oops
          token: ${{ secrets.GH_PAT }}
      - name: Checkout attempt for oops@${{ github.head_ref }}}
        if: github.event_name == 'pull_request'
        run: ./${{ env.BUNDLE }}/get-ref-branch ./${{ env.BUNDLE }}/oops

      - name: Build and Lint
        run: |
          docker run --rm \
            --entrypoint=/usr/local/src/${REPO}/${BUNDLE}/build-and-lint \
            --workdir=/usr/local/src/${REPO}/${BUNDLE} \
            --volume ${PWD}/${BUNDLE}:/usr/local/src/${REPO}/${BUNDLE} \
            'jcsda/docker-clang-mpich-dev:latest'
